### ISSUE TITLE
Multi-class labels identical each time?

### ISSUE THREAD

**Issue by martiansideofthemoon** [huggingface/transfer-learning-conv-ai#5]
I was wondering whether this piece of code was intentional - https://github.com/huggingface/transfer-learning-conv-ai/blob/master/train.py#L84

If I understand this correctly, the correct reply is always the last sequence among the candidates. Won't this encourage the multiple choice head classifier of the transformer to always predict the last class? (or am I missing something?)

**Comment by thomwolf** [comment]
HI @martiansideofthemoon, no it's not a problem, the model is invariant to the order of the sentence since we only use a linear layer to compute a score. Maybe you need to read the code a few time to be sure. The  GPT paper can help you understand that also (here: https://s3-us-west-2.amazonaws.com/openai-assets/research-covers/language-unsupervised/language_understanding_paper.pdf)

**Comment by martiansideofthemoon** [comment]
I missed the single layer part, thank you for your response and great repository!
